# Generated by Django 3.2.9 on 2021-11-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=10)),
                ('lte_exists', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
