# Generated by Django 3.2.9 on 2021-11-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.charfield>', max_length=100),
        ),
    ]
